// Vendor-specific payloads
export enum MailTemplateId {
  WELCOME = 'WELCOME',
  RESET_PASSWORD = 'RESET_PASSWORD',
  MAGIC_LINK = 'MAGIC_LINK',
  SUBSCRIPTION_TRIAL_START = 'SUBSCRIPTION_TRIAL_START',
  SUBSCRIPTION_TRIAL_END = 'SUBSCRIPTION_TRIAL_END',
  SUBSCRIPTION_ACTIVE = 'SUBSCRIPTION_ACTIVE',
  SUBSCRIPTION_PAST_DUE = 'SUBSCRIPTION_PAST_DUE',
}
