// Vendor-specific payloads
export enum MailTemplateId {
  WELCOME = 'WELCOME',
  SUBSCRIPTION_TRIAL_START = 'SUBSCRIPTION_TRIAL_START',
  SUBSCRIPTION_TRIAL_3D_LEFT = 'SUBSCRIPTION_TRIAL_3D_LEFT',
  SUBSCRIPTION_TRIAL_END = 'SUBSCRIPTION_TRIAL_END',
  SUBSCRIPTION_ACTIVE = 'SUBSCRIPTION_ACTIVE',
  SUBSCRIPTION_PAST_DUE = 'SUBSCRIPTION_PAST_DUE',
}
